name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        fail_ci_if_error: true

  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.20', '1.19', '1.18', '1.17', '1.16', '1.15', '1.14' ]
    name: Go ${{ matrix.go }} compatibility
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v
